### ISSUE TITLE
Offsetof implementation

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#276]
Standard requries stddef .h to be defined. 
Example implementation
```c
#define offsetof(s,m) ((size_t)&(((s*)0)->m))
```
That assumes that pointer to structure is stored in the linear memory. With current Cesium model I do not see obvious way how to implement that without resorting to intrinsic. And even then, I cannot see what intrinsic should we provide to implement this one feature

**Comment by ForNeVeR** [comment]
From my experiments: this doesn't seem to work in C#, even if it only uses `ldflda`:
```
struct Something
{
    public int memberA, memberB;
}

public class C {
    public unsafe static void Main() {
        var nullptr = ((Something*)null); 
        var offset = (byte*)&nullptr->memberB;
        Console.WriteLine((int)offset);
    }
}
```
It throws a `NullReferenceException` when trying to get `&nullptr->memberB`.

**Comment by ForNeVeR** [comment]
Some thoughts:
1. Yep, seems like this _has to_ be an intrinsic.
2. If the type information is available (and it necessarily is), then we should be able to implement that intrinsic easily*

* Obviously it won't be easy, since we'll have to duplicate the runtime code that calculates object layout. But still doable, since AFAIK the layout for `StructLayoutKind.Sequential` is standardized.
